name: rust-lambda-action
description: Deploy Rust lambdas
inputs:
  lambda_directory:
    description: the directory which has the lambda code
    required: true
  iam_role:
    description: the iam role required to deploy this lambda to production
    required: true

runs:
  using: composite
  steps:
    - name: Install cargo lambda
      run: |
        python -m pip install --upgrade pip
        pip install cargo-lambda
      shell: bash
    
    - uses: actions/checkout@v3
    - name: Build lambda function
      run: |
        cd ${{ inputs.lambda_directory }}
        cargo lambda build --release --arm64
      shell: bash      
    - name: Deploy lambda
      run: |
        cd ${{ inputs.lambda_directory }}
        pwd
        cargo lambda deploy --iam-role ${{ inputs.iam_role }} ${{ inputs.lambda_directory }}
      shell: bash

