name: rust-lambda-action
description: Deploy Rust lambdas
inputs:
  lambda_directory:
    description: the directory with the lambda code
    required: true

runs:
  using: composite
  steps:
    - name: Install cargo lambda
      run: |
        python -m pip install --upgrade pip
        pip install cargo-lambda
      shell: bash
    
    - uses: actions/checkout@v3
    - name: Build lambda function
      run: cargo lambda build --release --arm64
      shell: bash
      
    - name: Deploy lambda
      run: cargo lambda deploy --iam-role arn:aws:iam::285993504765:role/lambda-deployer ${{ inputs.lambda_directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SKYPE_SENDER_REGION }}
      shell: bash

