name: rust-lambda-action
description: Deploy Rust lambdas
inputs:
  lambda_directory:
    description: the directory which has the lambda code
    required: true
  iam_role:
    description: the iam role required to deploy this lambda to production
    required: true
  AWS_ACCESS_KEY_ID:
    description: aws access key id
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: aws secret access key
    required: true
  AWS_DEFAULT_REGION:
    description: aws default region
    required: true

runs:
  using: composite
  steps:
    - name: Install cargo lambda
      run: |
        python -m pip install --upgrade pip
        pip install cargo-lambda
      shell: bash
    
    - uses: actions/checkout@v3
    - name: Build lambda function
      run: |
        cd ${{ inputs.lambda_directory }}
        cargo lambda build --release --arm64
      shell: bash      
    - name: Deploy lambda
      run: |
        cd ${{ inputs.lambda_directory }}
        cargo lambda deploy --iam-role ${{ inputs.iam_role }} ${{ inputs.lambda_directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
      shell: bash

